const params = new URLSearchParams(window.location.search);
const project = window.PROJECTS.find((item) => item.slug === params.get('project'));
const root = document.querySelector('#project-page');

const materialManifest = {
  'tianjuli-film': { scripts: ['./materials/tianjuli-film/script/script-1.docx'], characters: ['./materials/tianjuli-film/人物/中国老人.png'], scenes: ['./materials/tianjuli-film/场景/城市高层.png', './materials/tianjuli-film/场景/窗外.jpg', './materials/tianjuli-film/场景/徽派小院.png', './materials/tianjuli-film/场景/乡间小路.png'], props: ['./materials/tianjuli-film/道具/盒子.png', './materials/tianjuli-film/道具/照片.png'], boards: ['./materials/tianjuli-film/分镜/田居里_00s.jpg', './materials/tianjuli-film/分镜/田居里_16s.png', './materials/tianjuli-film/分镜/田居里_24s.jpg', './materials/tianjuli-film/分镜/田居里_32s.jpg', './materials/tianjuli-film/分镜/田居里_40s.png', './materials/tianjuli-film/分镜/田居里_48s.jpg', './materials/tianjuli-film/分镜/田居里_56s.png', './materials/tianjuli-film/分镜/田居里_64s.png', './materials/tianjuli-film/分镜/田居里_72s.jpg', './materials/tianjuli-film/分镜/田居里_80s.jpg'] },
  'zaoya-film': { scripts: ['./materials/zaoya-film/script/script-1.docx'], characters: ['./materials/zaoya-film/人物/女主.png'], scenes: ['./materials/zaoya-film/场景/室内.png', './materials/zaoya-film/场景/室外.jpg'], props: ['./materials/zaoya-film/道具/咖啡.png', './materials/zaoya-film/道具/咖啡杯.png', './materials/zaoya-film/道具/咖啡盘.png', './materials/zaoya-film/道具/牛角包.png'], boards: ['./materials/zaoya-film/分镜/01.jpg', './materials/zaoya-film/分镜/02.jpg', './materials/zaoya-film/分镜/03.jpg', './materials/zaoya-film/分镜/04.jpg', './materials/zaoya-film/分镜/05.jpg', './materials/zaoya-film/分镜/06.jpg'] },
  'yimo-thousand-years': { scripts: ['./materials/yimo-thousand-years/script/script-1.docx'], characters: [{ src: './materials/yimo-thousand-years/人物/1-男1.png', label: '男主' }, { src: './materials/yimo-thousand-years/人物/1-男1三视图.png', label: '男主三视图' }, { src: './materials/yimo-thousand-years/人物/2-女主三视图.png', label: '女主三视图' }, { src: './materials/yimo-thousand-years/人物/3-男2三视图.png', label: '男二三视图' }], scenes: ['./materials/yimo-thousand-years/场景/副场景.png', './materials/yimo-thousand-years/场景/主场景.png'], props: [], boards: ['./materials/yimo-thousand-years/分镜/1.jpg', './materials/yimo-thousand-years/分镜/2-detail.jpg', './materials/yimo-thousand-years/分镜/3-detail.jpg', './materials/yimo-thousand-years/分镜/2.jpg', './materials/yimo-thousand-years/分镜/3.jpg', './materials/yimo-thousand-years/分镜/4.jpg', './materials/yimo-thousand-years/分镜/5.jpg', './materials/yimo-thousand-years/分镜/6.jpg', './materials/yimo-thousand-years/分镜/7.jpg', './materials/yimo-thousand-years/分镜/12-detail.jpg', './materials/yimo-thousand-years/分镜/9.jpg', './materials/yimo-thousand-years/分镜/14-detail.jpg', './materials/yimo-thousand-years/分镜/10.jpg', './materials/yimo-thousand-years/分镜/16-detail.jpg', './materials/yimo-thousand-years/分镜/17-detail.jpg', './materials/yimo-thousand-years/分镜/11.jpg'] },
  'changan-dream': { scripts: ['./materials/changan-dream/script/script-1.docx'], characters: ['./materials/changan-dream/人物/大人三视图.png', './materials/changan-dream/人物/皇帝三视图.png', './materials/changan-dream/人物/女主三视图-古代.png', './materials/changan-dream/人物/女主三视图-现代.png'], scenes: ['./materials/changan-dream/场景/场景1.png', './materials/changan-dream/场景/场景2.png', './materials/changan-dream/场景/场景3.png', './materials/changan-dream/场景/场景4.png'], props: ['./materials/changan-dream/道具/灯.png'], boards: ['./materials/changan-dream/分镜/1.png', './materials/changan-dream/分镜/2.png', './materials/changan-dream/分镜/4.png', './materials/changan-dream/分镜/6.png', './materials/changan-dream/分镜/7.png', './materials/changan-dream/分镜/8.png', './materials/changan-dream/分镜/9.png', './materials/changan-dream/分镜/10.png', './materials/changan-dream/分镜/11.png', './materials/changan-dream/分镜/12.png', './materials/changan-dream/分镜/13.png', './materials/changan-dream/分镜/14.png', './materials/changan-dream/分镜/15.png', './materials/changan-dream/分镜/16.png', './materials/changan-dream/分镜/17.png', './materials/changan-dream/分镜/18.png'] },
  'after-closing-my-eyes': { scripts: ['./materials/after-closing-my-eyes/script/script-1.docx', './materials/after-closing-my-eyes/script/script-2.docx', './materials/after-closing-my-eyes/script/script-3.docx'], characters: ['./materials/after-closing-my-eyes/人物/1.png', './materials/after-closing-my-eyes/人物/2.png', './materials/after-closing-my-eyes/人物/3.png', './materials/after-closing-my-eyes/人物/4.png'], scenes: ['./materials/after-closing-my-eyes/场景/1.png', './materials/after-closing-my-eyes/场景/2.png', './materials/after-closing-my-eyes/场景/3.png', './materials/after-closing-my-eyes/场景/4.png'], props: ['./materials/after-closing-my-eyes/道具/摩托车.png', './materials/after-closing-my-eyes/道具/汽车.png', './materials/after-closing-my-eyes/道具/手部细节1.png', './materials/after-closing-my-eyes/道具/手部细节2.png'], boards: ['./materials/after-closing-my-eyes/分镜/1-封面.png', './materials/after-closing-my-eyes/分镜/1.png', './materials/after-closing-my-eyes/分镜/3.png', './materials/after-closing-my-eyes/分镜/10.png', './materials/after-closing-my-eyes/分镜/11.png', './materials/after-closing-my-eyes/分镜/12.png', './materials/after-closing-my-eyes/分镜/14.png', './materials/after-closing-my-eyes/分镜/30.png', './materials/after-closing-my-eyes/分镜/33.png', './materials/after-closing-my-eyes/分镜/44.png', './materials/after-closing-my-eyes/分镜/48.png', './materials/after-closing-my-eyes/分镜/59.png', './materials/after-closing-my-eyes/分镜/66.png', './materials/after-closing-my-eyes/分镜/81.png', './materials/after-closing-my-eyes/分镜/85.png', './materials/after-closing-my-eyes/分镜/1-封底.png'] },
  'lamp-secret': { scripts: ['./materials/lamp-secret/script/script-1.docx', './materials/lamp-secret/script/script-2.docx'], characters: [{ src: './materials/lamp-secret/人物/男主.png', label: '男主' }, { src: './materials/lamp-secret/人物/女主苏小满.png', label: '女主 · 苏小满' }, { src: './materials/lamp-secret/人物/男主母亲.png', label: '男主母亲' }, { src: './materials/lamp-secret/人物/男2.png', label: '男二' }], scenes: ['./materials/lamp-secret/场景/茶室.png', './materials/lamp-secret/场景/灯楼.png', './materials/lamp-secret/场景/灯楼顶楼.png', './materials/lamp-secret/场景/古灯灯房.png'], props: ['./materials/lamp-secret/道具/被盖着的古灯.png', './materials/lamp-secret/道具/茶室屏风.png', './materials/lamp-secret/道具/古铜灯.png', './materials/lamp-secret/道具/铃铛.png'], boards: ['./materials/lamp-secret/分镜/2-2.png', './materials/lamp-secret/分镜/3-2.png', './materials/lamp-secret/分镜/3-3.png', './materials/lamp-secret/分镜/5-4.png', './materials/lamp-secret/分镜/5-5.png', './materials/lamp-secret/分镜/9-5.png', './materials/lamp-secret/分镜/10-1.png', './materials/lamp-secret/分镜/10-2.png', './materials/lamp-secret/分镜/10-3.png', './materials/lamp-secret/分镜/10-4.png', './materials/lamp-secret/分镜/11-1.png', './materials/lamp-secret/分镜/11-3.png', './materials/lamp-secret/分镜/11-5.png', './materials/lamp-secret/分镜/12-1.png', './materials/lamp-secret/分镜/12-3.png', './materials/lamp-secret/分镜/12-7.png'] },
  'night-walk': { scripts: ['./materials/night-walk/script/script-1.docx', './materials/night-walk/script/script-2.docx'], characters: ['./materials/night-walk/人物/男主.png', './materials/night-walk/人物/女主.png', './materials/night-walk/人物/女主2.png', './materials/night-walk/人物/丧尸女1.png'], scenes: ['./materials/night-walk/场景/别墅白.png', './materials/night-walk/场景/别墅厨房暗.png', './materials/night-walk/场景/别墅厨房黑.png', './materials/night-walk/场景/别墅客厅暗.png'], props: ['./materials/night-walk/道具/轮椅.png', './materials/night-walk/道具/摩托车.png', './materials/night-walk/道具/摩托车+人.png'], boards: ['./materials/night-walk/分镜/1-1.png', './materials/night-walk/分镜/1-2.jpg', './materials/night-walk/分镜/1-3.png', './materials/night-walk/分镜/2-4.png', './materials/night-walk/分镜/5-1.png', './materials/night-walk/分镜/5-10.jpg', './materials/night-walk/分镜/5-11.png', './materials/night-walk/分镜/7-5.jpg', './materials/night-walk/分镜/8-4.jpg', './materials/night-walk/分镜/8-5.png', './materials/night-walk/分镜/9-7.png', './materials/night-walk/分镜/10-0.png', './materials/night-walk/分镜/10-1.png', './materials/night-walk/分镜/10-2.png', './materials/night-walk/分镜/10-3.png', './materials/night-walk/分镜/10-6.jpg'] }
};

const brandCaseManifest = {
  'tianjuli-brand': { pdf: './materials/tianjuli-brand/田居里品牌案例.pdf', images: ['./materials/tianjuli-brand/case-study/case-1.jpg', './materials/tianjuli-brand/case-study/case-2.jpg', './materials/tianjuli-brand/case-study/case-3.jpg', './materials/tianjuli-brand/case-study/case-4.jpg', './materials/tianjuli-brand/case-study/case-5.jpg'] },
  'zaoya-brand': { pdf: './materials/zaoya-brand/AIGC商用案例.pdf', images: ['./materials/zaoya-brand/case-study/case-1.jpg', './materials/zaoya-brand/case-study/case-2.jpg', './materials/zaoya-brand/case-study/case-3.jpg', './materials/zaoya-brand/case-study/case-4.jpg'] },
  'jiuxin-brand': { pdf: './materials/jiuxin-brand/久新品牌案例.pdf', images: ['./materials/jiuxin-brand/case-study/case-1.jpg', './materials/jiuxin-brand/case-study/case-2.jpg', './materials/jiuxin-brand/case-study/case-3.jpg', './materials/jiuxin-brand/case-study/case-4.jpg', './materials/jiuxin-brand/case-study/case-5.jpg'] }
};

const safe = (src) => encodeURI(src);
const gallery = (title, images) => images.length ? `<section class="gallery-block"><h3>${title}</h3><div class="material-grid">${images.map((item, index) => { const src = typeof item === 'string' ? item : item.src; const label = typeof item === 'string' ? '查看大图 ↗' : item.label; return `<a href="${safe(src)}" target="_blank" rel="noreferrer"><img loading="lazy" src="${safe(src)}" alt="${title} ${label || index + 1}"><span>${label}</span></a>`; }).join('')}</div></section>` : '';
const escapeScript = (value = '') => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const scriptLineBreaks = (value) => escapeScript(value).replace(/\n/g, '<br>');
const scriptTable = (table) => {
  const [head, ...rows] = table;
  return `<div class="script-table-wrap"><table class="script-table script-table--${head.length}"><thead><tr>${head.map((cell) => `<th>${scriptLineBreaks(cell)}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${scriptLineBreaks(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
};
const scriptReader = (document) => {
  if (!document) return '';
  const tables = [...document.tables];
  const mainIndex = tables.length ? tables.reduce((largest, table, index) => table.length > tables[largest].length ? index : largest, 0) : -1;
  const main = mainIndex >= 0 ? tables.splice(mainIndex, 1)[0] : null;
  return `<div class="inline-script-reader"><p class="script-reader-note">根据《${escapeScript(document.source)}》整理。表格可横向滑动查看完整列。</p>${main ? scriptTable(main) : ''}</div>`;
};

if (!project) {
  root.innerHTML = '<section class="empty"><p class="eyebrow">PROJECT NOT FOUND</p><h1>未找到这个项目</h1><a class="button dark" href="./index.html">返回作品集</a></section>';
} else {
  document.title = `${project.title}｜王京琪作品集`;
  const material = materialManifest[project.slug];
  const brandCase = brandCaseManifest[project.slug];
  const scriptDocument = window.SCRIPT_DOCS ? window.SCRIPT_DOCS[project.slug] : null;
  const video = project.video ? `<section id="film" class="video-section"><video controls playsinline poster="${project.cover}"><source src="${project.video}" type="video/mp4">你的浏览器暂不支持视频播放。</video></section>` : '';
  const background = project.background ? `<section id="background" class="detail-section project-background"><p class="eyebrow">PROJECT BACKGROUND</p><h2>项目背景</h2><p class="body-copy">${project.background}</p></section>` : '';
  const navigation = material ? `<nav class="project-navigation"><a href="#background">01 项目背景</a><a href="#script">02 脚本</a><a href="#assets">03 人物 / 场景 / 道具</a><a href="#storyboard">04 关键分镜</a><a href="#making">05 AI 生成与后期</a></nav>` : brandCase ? `<nav class="project-navigation brand-navigation"><a href="#case-study">查看完整案例</a><a href="${safe(brandCase.pdf)}" target="_blank" rel="noreferrer">打开原始 PDF ↗</a></nav>` : '';
  const script = project.story ? `<section id="script" class="detail-section narrow script-${project.slug}"><p class="eyebrow">SCRIPT</p><h2>脚本与叙事设定</h2><p class="body-copy">${project.story}</p>${scriptReader(scriptDocument)}</section>` : '';
  const settings = material ? `<section id="assets" class="asset-library"><div class="asset-wrap"><p class="eyebrow">CHARACTER / SCENE / PROP</p><h2>人物、场景与道具设定</h2><p>用于保持跨镜头的角色、场景和道具连续性；点击图片可查看大图。</p>${gallery('人物设定', material.characters)}${gallery('场景设定', material.scenes)}${gallery('道具设定', material.props)}</div></section>` : '';
  const storyboard = project.storyboard ? `<section id="storyboard" class="detail-section"><p class="eyebrow">KEY STORYBOARDS</p><h2>关键分镜</h2><ol class="storyboard">${project.storyboard.map((line, index) => `<li><span>${String(index + 1).padStart(2, '0')}</span><p>${line}</p></li>`).join('')}</ol>${material ? gallery('分镜画面', material.boards) : ''}</section>` : '';
  const workflow = project.workflow ? `<section id="workflow" class="workflow"><p class="eyebrow">AI PRODUCTION WORKFLOW</p><h2>无限画布制作工作流</h2><p>将人物、场景、镜头与生成步骤铺陈在同一画布中，用于保持连续剧情下的视觉和生产节奏。</p><div>${project.workflow.map((src, index) => `<a href="${safe(src)}" target="_blank" rel="noreferrer"><img loading="lazy" src="${safe(src)}" alt="${project.title}工作流 ${index + 1}"></a>`).join('')}</div></section>` : '';
  const making = material ? `<section id="making" class="making-section"><p class="eyebrow">AI GENERATION / POST-PRODUCTION</p><h2>AI 生成与后期</h2><p>作品由脚本、人物与场景设定、分镜画面及剪辑包装共同完成。完整成片可在本页视频播放器观看。</p><div class="making-actions">${project.workflow ? '<a class="making-link" href="#workflow">查看暗夜同行工作流 ↘</a>' : ''}<a class="making-link" href="#film">观看成片 ↗</a></div></section>` : '';
  const caseStudy = brandCase ? `<section id="case-study" class="case-study"><div><p class="eyebrow">FULL CASE STUDY</p><h2>完整项目展示</h2><p>以下内容来自原始案例文档，保留完整视觉与项目过程。</p><a class="making-link" href="${safe(brandCase.pdf)}" target="_blank" rel="noreferrer">打开原始 PDF ↗</a></div>${brandCase.images.map((src, index) => `<img loading="lazy" src="${safe(src)}" alt="${project.title}完整案例 ${index + 1}">`).join('')}</section>` : '';
  const cover = project.cover ? `<img src="${safe(project.cover)}" alt="${project.title}项目封面">` : `<div class="generated-cover"><span>${project.english}</span><b>${project.title}</b></div>`;
  root.innerHTML = `<section class="project-hero"><div><p class="eyebrow">${project.category} / ${project.year}</p><h1>${project.title}</h1><p class="type">${project.type}${project.duration ? ` · ${project.duration}` : ''}</p><p class="statement-copy">${project.statement}</p></div><div class="detail-cover">${cover}</div></section>${navigation}${video}${background}<section class="detail-section intro"><p class="eyebrow">PROJECT OVERVIEW · 项目概述</p><h2>${project.overview}</h2></section><section class="role-grid"><div><p class="eyebrow">MY ROLE · 我的职责</p><p>${project.role}</p></div><div><p class="eyebrow">CREATIVE FOCUS · 创作重点</p><ul>${project.focus.map((line) => `<li>${line}</li>`).join('')}</ul></div></section>${caseStudy}${script}${settings}${storyboard}${workflow}${making}<div class="project-return"><a href="#project-page">回到项目开头 <span>↑</span></a></div>`;
}
